stages:
  - prepare

prepare_job:
  stage: prepare
  image: node:12.10-alpine
  rules:
    - if: $CI_COMMIT_TAG
      when: always
    - when: never
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - "dist"
    expire_in: never
